import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TopNavbar } from "@/components/layout/TopNavbar";
import { Toaster } from "@/components/ui/sonner"; // Assuming sonner was added to ui components by shadcn cli

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Frontend App with Go Backend",
  description: "Generated by Manus AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable
        )}
      >
        <TopNavbar />
        <main className="container mx-auto px-4 py-8 flex-grow">
          {children}
        </main>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}

